import selfcord

print(f"selfcord v{selfcord.__version__} is installed and ready.")
print("This is a Python library for interacting with Discord's user API.")
print()
print("Example usage:")
print("  import selfcord")
print()
print("  client = selfcord.Client()")
print()
print("  @client.event")
print("  async def on_ready():")
print("      print(f'Logged in as {client.user}')")
print()
print("  client.run('your-token-here')")
print()
print("See the examples/ directory for more usage examples.")
